fire=part_type_create()
    part_type_alpha2(fire,1,0)
    part_type_colour2(fire,c_red,c_yellow)
    part_type_shape(fire,pt_shape_disk)
    part_type_life(fire,30,60)
    part_type_speed(fire,1.2,1.8,0,0)
    part_type_direction(fire,70,110,0,0)
    part_type_size(fire,0.05,0.2,0,0)

water=part_type_create()
    part_type_alpha2(water,1,0)
    part_type_colour2(water,c_blue,c_blue)
    part_type_shape(water,pt_shape_disk)
    part_type_life(water,30,60)
    part_type_size(water,0.04,0.15,0,0)
    part_type_gravity(water,0.03,270)

ice=part_type_create()
    part_type_alpha2(ice,1,0)
    part_type_colour2(ice,c_aqua,c_aqua)
    part_type_shape(ice,pt_shape_disk)
    part_type_life(ice,30,60)
    part_type_size(ice,0.05,0.2,0,0)    

electric=part_type_create()
    part_type_alpha2(electric,1,0)
    part_type_colour2(electric,c_yellow,c_yellow)
    part_type_shape(electric,pt_shape_flare)
    part_type_life(electric,30,60)
    part_type_direction(electric,0,360,0,0)
    part_type_speed(electric,1.4,2,0,0)
    part_type_size(electric,0.1,0.3,0,0)    
    
air=part_type_create()
    part_type_alpha2(air,1,0)
    part_type_colour2(air,c_white,c_gray)
    part_type_shape(air,pt_shape_disk)
    part_type_life(air,30,60)
    part_type_direction(air,0,360,0,0)
    part_type_speed(air,1.4,2,0,0)
    part_type_size(air,0.04,0.15,0,0)    

poison=part_type_create()
    part_type_alpha2(poison,1,0)
    part_type_colour2(poison,c_lime,c_green)
    part_type_shape(poison,pt_shape_disk)
    part_type_life(poison,30,60)
    part_type_direction(poison,0,360,0,0)
    part_type_speed(poison,0.3,0.6,0,0)
    part_type_gravity(poison,0.02,90)
    part_type_size(poison,0.1,0.25,0,0)    

light=part_type_create()
    part_type_alpha2(light,0.5,0)
    part_type_colour2(light,c_white,c_white)
    part_type_shape(light,pt_shape_disk)
    part_type_life(light,30,60)
    part_type_direction(light,0,360,0,0)
    part_type_speed(light,0.3,0.6,0,0)
    part_type_size(light,0.1,0.25,0,0)
        
dark=part_type_create()
    part_type_alpha2(dark,0.5,0)
    part_type_colour2(dark,c_purple,c_purple)
    part_type_shape(dark,pt_shape_disk)
    part_type_life(dark,30,60)
    part_type_direction(dark,0,360,0,0)
    part_type_speed(dark,0.3,0.6,0,0)
    part_type_size(dark,0.1,0.25,0,0.05)    

create_effect_particles_3()
