combination_map=ds_map_create()

//Fire + ?
ds_map_add(combination_map,'firefire','Flamethrower')
ds_map_add(combination_map,'firewater','none')
ds_map_add(combination_map,'fireice','none')
ds_map_add(combination_map,'fireair','Firenado')
ds_map_add(combination_map,'fireelectric','Flame Zap')
ds_map_add(combination_map,'firepoison','Greek Fire')
ds_map_add(combination_map,'firelight','Holy Flame')
ds_map_add(combination_map,'firedark','Dark Flame')
ds_map_add(combination_map,'firebomb','Fire Bomb')
ds_map_add(combination_map,'firemetal','Fire Sword')

//Water + ?
ds_map_add(combination_map,'waterfire','none')
ds_map_add(combination_map,'waterwater','Flood')
ds_map_add(combination_map,'waterice','Slush')
ds_map_add(combination_map,'waterair','Waternado')
ds_map_add(combination_map,'waterelectric','Water Zap')
ds_map_add(combination_map,'waterpoison','Acid Rain')
ds_map_add(combination_map,'waterlight','Holy Water')
ds_map_add(combination_map,'waterdark','Evil Water')
ds_map_add(combination_map,'waterbomb','Water Bomb')
ds_map_add(combination_map,'watermetal','Water Sword')

//Ice + ?
ds_map_add(combination_map,'icefire','none')
ds_map_add(combination_map,'icewater','Slush')
ds_map_add(combination_map,'iceice','Ice Spike')
ds_map_add(combination_map,'iceair','Icenado')
ds_map_add(combination_map,'iceelectric','Ice Zap')
ds_map_add(combination_map,'icepoison','Acid Spike')
ds_map_add(combination_map,'icelight','Snow')
ds_map_add(combination_map,'icedark','Dark Spike')
ds_map_add(combination_map,'icebomb','Ice Bomb')
ds_map_add(combination_map,'icemetal','Ice Sword')

//Air + ?
ds_map_add(combination_map,'airfire','Firenado')
ds_map_add(combination_map,'airwater','Waternado')
ds_map_add(combination_map,'airice','Icenado')
ds_map_add(combination_map,'airair','Cyclone')
ds_map_add(combination_map,'airelectric','Thunderstorm')
ds_map_add(combination_map,'airpoison','Toxic Cloud')
ds_map_add(combination_map,'airlight','Light Blast')
ds_map_add(combination_map,'airdark','Dark Blast')
ds_map_add(combination_map,'airbomb','Wind Bomb')
ds_map_add(combination_map,'airmetal','Air Sword')

//Electric + ?
ds_map_add(combination_map,'electricfire','Flame Zap') 
ds_map_add(combination_map,'electricwater','Water Zap')
ds_map_add(combination_map,'electricice','Ice Zap')
ds_map_add(combination_map,'electricair','Thunderstorm')
ds_map_add(combination_map,'electricelectric','Lightning')
ds_map_add(combination_map,'electricpoison','Poison Zap')
ds_map_add(combination_map,'electriclight','Lightbulb')
ds_map_add(combination_map,'electricdark','Dark Zap')
ds_map_add(combination_map,'electricbomb','Electric Bomb')
ds_map_add(combination_map,'electricmetal','Electric Sword')

//Poison + ?
ds_map_add(combination_map,'poisonfire','Greek Fire')
ds_map_add(combination_map,'poisonwater','Acid Rain')
ds_map_add(combination_map,'poisonice','Acid Spike')
ds_map_add(combination_map,'poisonair','Toxic Cloud')
ds_map_add(combination_map,'poisonelectric','Poison Zap')
ds_map_add(combination_map,'poisonpoison','Toxic Spill')
ds_map_add(combination_map,'poisonlight','none')
ds_map_add(combination_map,'poisondark','Death')
ds_map_add(combination_map,'poisonbomb','Acid Bomb')
ds_map_add(combination_map,'poisonmetal','Poison Sword')

//Light + ?
ds_map_add(combination_map,'lightfire','Holy Flame')
ds_map_add(combination_map,'lightwater','Holy Water')
ds_map_add(combination_map,'lightice','Snow')
ds_map_add(combination_map,'lightair','Light Blast')
ds_map_add(combination_map,'lightelectric','Lightbulb')
ds_map_add(combination_map,'lightpoison','none')
ds_map_add(combination_map,'lightlight','Holy Aura')
ds_map_add(combination_map,'lightdark','none')
ds_map_add(combination_map,'lightbomb','Purification')
ds_map_add(combination_map,'lightmetal','Light Sword')

//Dark + ?
ds_map_add(combination_map,'darkfire','Dark Flame')
ds_map_add(combination_map,'darkwater','Evil Water')
ds_map_add(combination_map,'darkice','Dark Spike')
ds_map_add(combination_map,'darkair','Dark Blast')
ds_map_add(combination_map,'darkelectric','Dark Zap')
ds_map_add(combination_map,'darkpoison','Death')
ds_map_add(combination_map,'darklight','none')
ds_map_add(combination_map,'darkdark','Evil Aura')
ds_map_add(combination_map,'darkbomb','Corruption')
ds_map_add(combination_map,'darkmetal','Dark Sword')

//Bomb + ?
ds_map_add(combination_map,'bombfire','Fire Bomb')
ds_map_add(combination_map,'bombwater','Water Bomb')
ds_map_add(combination_map,'bombice','Ice Bomb')
ds_map_add(combination_map,'bombair','Wind Bomb')
ds_map_add(combination_map,'bombelectric','Electric Bomb')
ds_map_add(combination_map,'bombpoison','Acid Bomb')
ds_map_add(combination_map,'bomblight','Purification')
ds_map_add(combination_map,'bombdark','Corruption')
ds_map_add(combination_map,'bombbomb','Nuke')
ds_map_add(combination_map,'bombmetal','Mine')

//Metal + ?
ds_map_add(combination_map,'metalfire','Fire Sword')
ds_map_add(combination_map,'metalwater','Water Sword')
ds_map_add(combination_map,'metalice','Ice Sword')
ds_map_add(combination_map,'metalair','Air Sword')
ds_map_add(combination_map,'metalelectric','Electric Sword')
ds_map_add(combination_map,'metalpoison','Poison Sword')
ds_map_add(combination_map,'metallight','Light Sword')
ds_map_add(combination_map,'metaldark','Dark Sword')
ds_map_add(combination_map,'metalbomb','Mine')
ds_map_add(combination_map,'metalmetal','Shuriken')
