effect=part_system_create()
part_system_depth(effect,-50)

burn=part_type_create()
    part_type_alpha2(burn,1,0)
    part_type_colour2(burn,c_red,c_yellow)
    part_type_shape(burn,pt_shape_square)
    part_type_life(burn,30,60)
    part_type_speed(burn,1.2,1.8,0,0)
    part_type_direction(burn,70,110,0,0)
    part_type_size(burn,0.05,0.2,0,0)
    
pois=part_type_create()
    part_type_alpha2(pois,1,0)
    part_type_colour2(pois,c_lime,c_green)
    part_type_shape(pois,pt_shape_square)
    part_type_life(pois,30,60)
    part_type_speed(pois,0.5,1,0,0)
    part_type_direction(pois,70,110,0,0)
    part_type_size(pois,0.05,0.2,0,0)

slow=part_type_create()
    part_type_alpha2(slow,1,0)
    part_type_colour2(slow,c_white,c_gray)
    part_type_shape(slow,pt_shape_square)
    part_type_life(slow,30,60)
    part_type_size(slow,0.1,0.2,0,0)
    part_type_gravity(slow,0.02,270)

stun=part_type_create()
    part_type_alpha2(stun,1,0)
    part_type_colour2(stun,c_yellow,c_yellow)
    part_type_shape(stun,pt_shape_square)
    part_type_life(stun,20,40)
    part_type_size(stun,0.1,0.2,0,0)
    
create_effect_particles_2()
