clash=part_type_create()
    part_type_alpha3(clash,1,1,0)
    part_type_colour3(clash,c_red,c_orange,c_yellow)
    part_type_shape(clash,pt_shape_spark)
    part_type_direction(clash,0,360,0,0)
    part_type_life(clash,20,40)
    part_type_size(clash,0.1,0.4,0,0)
    part_type_speed(clash,2,4,-0.1,0)
    part_type_gravity(clash,0.01,270)
    
blood=part_type_create()
    part_type_alpha3(blood,1,1,0)
    part_type_colour1(blood,c_red)
    part_type_shape(blood,pt_shape_square)
    part_type_direction(blood,0,360,0,0)
    part_type_life(blood,20,40)
    part_type_size(blood,0.02,0.1,0,0)
    part_type_speed(blood,1.5,3,-0.08,0)
    part_type_gravity(blood,0.04,270)
    
explode=part_type_create()
    part_type_alpha3(explode,1,1,0)
    part_type_shape(explode,pt_shape_flare)
    part_type_direction(explode,0,360,0,0)
    part_type_life(explode,30,40)
    part_type_size(explode,0.3,0.8,-0.02,0)
    part_type_speed(explode,1.5,3,-0.08,0)
    part_type_gravity(explode,0.04,270)  

cloud=part_type_create()
    part_type_alpha3(cloud,1,1,0)
    part_type_colour2(cloud,c_green,c_dkgray)
    part_type_shape(cloud,pt_shape_smoke)
    part_type_life(cloud,30,40)
    part_type_size(cloud,0.3,0.8,-0.02,0)
    part_type_gravity(cloud,0.04,270)  

greek=part_type_create()
    part_type_alpha2(greek,1,0)
    part_type_colour2(greek,c_lime,c_green)
    part_type_shape(greek,pt_shape_square)
    part_type_life(greek,30,60)
    part_type_speed(greek,1.2,1.8,0,0)
    part_type_direction(greek,70,110,0,0)
    part_type_size(greek,0.05,0.2,0,0)

flame_holy=part_type_create()
    part_type_alpha2(flame_holy,1,0)
    part_type_colour2(flame_holy,c_white,c_ltgray)
    part_type_shape(flame_holy,pt_shape_square)
    part_type_life(flame_holy,30,60)
    part_type_speed(flame_holy,1.2,1.8,0,0)
    part_type_direction(flame_holy,70,110,0,0)
    part_type_size(flame_holy,0.05,0.2,0,0)

flame_dark=part_type_create()
    part_type_alpha2(flame_dark,1,0)
    part_type_colour2(flame_dark,c_fuchsia,c_purple)
    part_type_shape(flame_dark,pt_shape_square)
    part_type_life(flame_dark,30,60)
    part_type_speed(flame_dark,1.2,1.8,0,0)
    part_type_direction(flame_dark,70,110,0,0)
    part_type_size(flame_dark,0.05,0.2,0,0)

water_purple=part_type_create()
    part_type_alpha2(water_purple,1,0)
    part_type_colour2(water_purple,c_purple,c_purple)
    part_type_shape(water_purple,pt_shape_disk)
    part_type_life(water_purple,30,60)
    part_type_size(water_purple,0.04,0.15,0,0)
    part_type_gravity(water_purple,0.03,270)
 
emit=part_emitter_create(effect)
