hue0=colour_get_hue(colours[| 0])
hue1=colour_get_hue(colours[| 1])
sat0=colour_get_saturation(colours[| 0])
sat1=colour_get_saturation(colours[| 1])
val0=colour_get_value(colours[| 0])
val1=colour_get_value(colours[| 1])
